development:
  adapter: postgresql
  encoding: utf8
  database: frackers_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: pfrackerstest
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: frackers_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
